// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),

// Autocombat System
BUILDIN_DEF(ac_getskillinfostring, "iv"),
BUILDIN_DEF(ac_setautocombat, "s"),
BUILDIN_DEF(autocombat_fromitem, "i"),
BUILDIN_DEF(ac_getautocombatstring, "i??"),
BUILDIN_DEF(ac_getautocombatint, "i?"),
BUILDIN_DEF(ac_getstate, ""),
