// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Atcommands
 * Place the definition of custom atcommands in this file.
 * Format:
 *	ACMD_DEF(command_name),
 **/

//ACMD_DEF(newcommand),
ACMD_DEF(afk),
ACMD_DEF(basicbonuses),
ACMD_DEF(extendedbonuses),
ACMD_DEF(gspecificbonuses),
ACMD_DEF(srelatedbonuses),
ACMD_DEF(autospellbonuses),
ACMD_DEF(miscbonuses),
ACMD_DEF(mobinfo2),
ACMD_DEF(statbonus),
ACMD_DEF2("mercenaryon", mercenaryon),
ACMD_DEF(reloadcollectiondb),
ACMD_DEF(whodrops2),
ACMD_DEF(whosell),
ACMD_DEF(whobuy),
ACMD_DEF(reloadrunedb),
