// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/

// autocombat
int32 function_autocombat_autoheal;
int32 function_autocombat_autopotion;
int32 function_autocombat_sittorest;
int32 function_autocombat_attackskill;
int32 function_autocombat_buffskill;
int32 function_autocombat_buffitems;
int32 function_autocombat_teleport;
int32 function_autocombat_teleport_mvp;
int32 function_autocombat_pickup;
int32 function_autocombat_prefixname;
int32 function_autocombat_hateffect;
int32 function_autocombat_pdetection;
int32 function_autocombat_mselection;
int32 function_autocombat_mdetection;
int32 function_autocombat_pickup_delay;
int32 function_autocombat_move_min;
int32 function_autocombat_move_max;
int32 function_autocombat_movetype;
int32 function_autocombat_askill_delay;
int32 function_autocombat_bskill_delay;
int32 function_autocombat_drop_ratio;
int32 function_autocombat_exp_ratio;
int32 function_autocombat_allow_town;
int32 function_autocombat_allow_pvp;
int32 function_autocombat_allow_gvg;
int32 function_autocombat_allow_bg;
int32 function_autocombat_duration_type;
int32 function_autocombat_timer;
int32 function_autocombat_iplimit;
int32 function_autocombat_gepardlimit;