// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/

// autocombat
int32 autocombat_autoheal;
int32 autocombat_autopotion;
int32 autocombat_sittorest;
int32 autocombat_attackskill;
int32 autocombat_buffskill;
int32 autocombat_buffitems;
int32 autocombat_teleport;
int32 autocombat_teleport_mvp;
int32 autocombat_pickup;
int32 autocombat_prefixname;
int32 autocombat_hateffect;
int32 autocombat_pdetection;
int32 autocombat_mselection;
int32 autocombat_mdetection;
int32 autocombat_pickup_delay;
int32 autocombat_move_min;
int32 autocombat_move_max;
int32 autocombat_movetype;
int32 autocombat_askill_delay;
int32 autocombat_bskill_delay;
int32 autocombat_drop_ratio;
int32 autocombat_exp_ratio;
int32 autocombat_allow_town;
int32 autocombat_allow_pvp;
int32 autocombat_allow_gvg;
int32 autocombat_allow_bg;
int32 autocombat_duration_type;
int32 autocombat_timer;
int32 autocombat_iplimit;
int32 autocombat_gepardlimit;